# Catppuccin Format
format = """
[â–’â–“](mantle)\
$directory\
[î‚°](fg:mantle bg:lavender)\
$git_branch\
$git_status\
[î‚° ](fg:lavender)\
"""


right_format = """
$python\
$cmd_duration\
$nodejs\
$battery\
"""
# [â–‘â–’â–“](#6272a4)\
palette = "catppuccin_mocha"
# add_newline = false

# Replace the 'â¯' symbol in the prompt with 'âœ'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[â¯â¯](bold green)'
# error_symbol = '[â¯â¯](bold red)'# The 'successcd_symbol' segment is being set to 'âœ' with the color 'bold green'

# [username]
# show_always = true
# style_user = "bg:#282A36 fg:#bd93f9 bold"
# style_root = "bg:#bd93f9 fg:#000000 italic"
# format = '[ $user ]($style)'
# disabled = false


[directory]
style = "fg:lavender bg:mantle"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "â€¦/"

[directory.substitutions]
# "Documents" = " ïœ˜ "
# "Downloads" = " ï€™ "
# # "Music/" = "ï€/"
# "Pictures" = " ï€¾ "
# "/mnt/DATA" = " ïŸ› "
# "~/github.com/" = "http://github.com"

[git_branch]
symbol = "îœ¥"
style = "bg:lavender"
format = '[[ $symbol $branch ](fg:mantle bg:lavender)]($style)'

[git_status]
style = "bg:lavender"
format = '[[($all_status$ahead_behind )](fg:mantle bg:lavender)]($style)'

[python]
symbol = 'ğŸ '
format = '[ ${symbol} ${pyenv_prefix}]($style)'

[nodejs]
symbol = "îœ˜"
format = '[[ $symbol($version)](fg:#ff5555)]($style)'

[battery]
format = '[ ïƒ§$percentage]($style)'

[[battery.display]]
threshold = 50
style = 'fg:#50fa7b'


[cmd_duration]
min_time = 1000
format = ' [$duration](bold yellow)'
#
# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#282A36 fg:blue bold"
# format = '[[ $time ](bg:base fg:lavender bold)]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
